//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RevisoftApplication.it.revisoft.ws {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="revisoftWSSoap", Namespace="http://www.revisoft.it/soap/revisoftWS")]
    public partial class revisoftWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback statisticheWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback versioniWSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public revisoftWS() {
            this.Url = global::RevisoftApplication.Properties.Settings.Default.RevisoftApplication_it_revisoft_ws_revisoftWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event statisticheWSCompletedEventHandler statisticheWSCompleted;
        
        /// <remarks/>
        public event versioniWSCompletedEventHandler versioniWSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.revisoft.it/soap/revisoftWS/statisticheWS", RequestNamespace="http://www.revisoft.it/soap/revisoftWS", ResponseNamespace="http://www.revisoft.it/soap/revisoftWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string statisticheWS(string xml) {
            object[] results = this.Invoke("statisticheWS", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void statisticheWSAsync(string xml) {
            this.statisticheWSAsync(xml, null);
        }
        
        /// <remarks/>
        public void statisticheWSAsync(string xml, object userState) {
            if ((this.statisticheWSOperationCompleted == null)) {
                this.statisticheWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstatisticheWSOperationCompleted);
            }
            this.InvokeAsync("statisticheWS", new object[] {
                        xml}, this.statisticheWSOperationCompleted, userState);
        }
        
        private void OnstatisticheWSOperationCompleted(object arg) {
            if ((this.statisticheWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.statisticheWSCompleted(this, new statisticheWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.revisoft.it/soap/revisoftWS/versioniWS", RequestNamespace="http://www.revisoft.it/soap/revisoftWS", ResponseNamespace="http://www.revisoft.it/soap/revisoftWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string versioniWS(string xml) {
            object[] results = this.Invoke("versioniWS", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void versioniWSAsync(string xml) {
            this.versioniWSAsync(xml, null);
        }
        
        /// <remarks/>
        public void versioniWSAsync(string xml, object userState) {
            if ((this.versioniWSOperationCompleted == null)) {
                this.versioniWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnversioniWSOperationCompleted);
            }
            this.InvokeAsync("versioniWS", new object[] {
                        xml}, this.versioniWSOperationCompleted, userState);
        }
        
        private void OnversioniWSOperationCompleted(object arg) {
            if ((this.versioniWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.versioniWSCompleted(this, new versioniWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void statisticheWSCompletedEventHandler(object sender, statisticheWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class statisticheWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal statisticheWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void versioniWSCompletedEventHandler(object sender, versioniWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class versioniWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal versioniWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591